### ISSUE TITLE
`dart run realm generate` stopped working and no error was reported

### ISSUE THREAD

**Issue by dotjon0** [realm/realm-dart#1317]
### What happened?

The following command has stopped working...

`dart run realm generate`

### Repro steps

When running `dart run realm generate` the below is outputted in the terminal, no errors are reported in the terminal and no `.g` auto generated realm files are generated... 

```
Building package executable... (1.5s)
Built realm:realm.
```

We have tried `flutter pub clean cache` and `flutter clean` and reinstalled `flutter pub get`, with no luck.

### Version

realm 1.2.0, flutter 3.10.1

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### What type of application is this?

Flutter Application

### Client OS and version

MacOS 13.3.1

**Comment by desistefanova** [comment]
Hi @dotjon0!
We will investigate that.
Meanwhile, you can try to upgrade to flutter 3.10.4 and to check if you will have the same issue.
You can also try `flutter pub run build_runner build --delete-conflicting-outputs` or `dart run build_runner build --delete-conflicting-outputs`

**Comment by dotjon0** [comment]
thank you @desistefanova. we have tried upgrading to flutter 3.10.4 and it made no difference.

when we run `flutter pub run build_runner build --delete-conflicting-outputs` it forces us to add the dependency `build_runner: ^2.4.5`, which we added. However when running `flutter pub run build_runner build --delete-conflicting-outputs` or `dart run build_runner build --delete-conflicting-outputs` it then gives the following error in the terminal:

```
Building package executable... (1.3s)
Failed to build build_runner:build_runner:
../../../../.pub-cache/hosted/pub.dev/build_runner_core-7.2.6/lib/src/logging/build_for_input_logger.dart:13:7: Error: The non-abstract class 'BuildForInputLogger' is missing implementations for these members:
 - Logger.onLevelChanged
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class BuildForInputLogger implements Logger {
      ^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/logging-1.2.0/lib/src/logger.dart:162:22: Context: 'Logger.onLevelChanged' is defined here.
  Stream<Level?> get onLevelChanged {

```

**Comment by desistefanova** [comment]
What if you run:
`dart run realm generator --clean`
and then 
`dart run realm generator`?
This should force the generating.

**Comment by dotjon0** [comment]
`dart run realm generator --clean` gives me this error in the terminal:

```
Building package executable... 
Built realm:realm.
Could not find an option named "clean".

Usage: dart run realm|realm_dart <command> [arguments]

Global options:
-h, --help    Print this usage information.

Available commands:
  generate   Generate Realm objects from data model classes
  install    Download & install Realm native binaries into a Flutter or Dart project
  metrics    Report anonymized builder metrics to Realm

Run "dart run realm|realm_dart help <command>" for more information about a command.

```

Then `dart run realm generator` gave me:

Building package executable... 
Built realm:realm.
Could not find a command named "generator".

Did you mean one of these?
  generate


Usage: dart run realm|realm_dart <command> [arguments]

Global options:
-h, --help    Print this usage information.

Available commands:
  generate   Generate Realm objects from data model classes
  install    Download & install Realm native binaries into a Flutter or Dart project
  metrics    Report anonymized builder metrics to Realm

Run "dart run realm|realm_dart help <command>" for more information about a command.

Perhaps 'generator' was meant to be 'generate', in which case I get the following and the .g auto generated files still fail to appear:

`dart run realm generate --clean`:
`Building package executable... 
Built realm:realm.
`

`dart run realm generator`:
`Building package executable... 
Built realm:realm.
`

**Comment by dotjon0** [comment]
No we did not have `build_runner` before, so I removed `build_runner` and I get the same (as below) with no .g files auto generated...dart run 
```
realm generate --clean:
Building package executable...  Built realm:realm. 
```

```
dart run realm generate:
Building package executable...  Built realm:realm. 
```

**Comment by desistefanova** [comment]
Ahh, yes.
It happens to me, but only on the Mac OS. 
It works on Windows and Linux.
I will investigate it.
Thanks for reporting.

**Comment by dotjon0** [comment]
Ah brilliant you can replicate. Thanks for confirming

**Comment by desistefanova** [comment]
This error is appears because of the `logging` package that is implemented inside `build_runner core`. The issue is fixed in `build_runner core`. In order to get the fix, just run:

-  `dart pub upgrade`
and then 
- `dart run realm generate`

**Comment by dotjon0** [comment]
Ah yes I thought it was strange the `logging` package was throwing an error in the above thread. So I tried what you suggested and it did not work, so I then re-added the `build_runner: ^2.4.5` as a dev dependency (even though we do not use `build_runner`) and retried what you suggested (`dart pub upgrade` and `dart run realm generate`) and it worked. Thank you so much for your help on this.

**Comment by desistefanova** [comment]
Great!
`build_runner: ^2.4.5` shouldn't be needed in the dependencies. Probably, if you try to clean and get the packages again it will be fixed. 
Yes, definitely, we will check why the error is not reported to the console.

**Comment by dotjon0** [comment]
Thank you so much again @desistefanova

**Comment by abcdedf** [comment]
Hello, 
'dart run realm generate'  command works, but build_runner still fails.
We are using stable channel and following is the output of flutter --version
$ flutter --version
Flutter 3.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 796c8ef792 (4 weeks ago) • 2023-06-13 15:51:02 -0700
Engine • revision 45f6e00911
Tools • Dart 3.0.5 • DevTools 2.23.1

We tried with build_runner versions below and both failed with same output as below.
build_runner: ^2.3.3
build_runner: ^2.4.6

dart run build_runner build --delete-conflicting-outputs    -- produces the output below.
Building package executable... (2.0s)
Failed to build build_runner:build_runner:
../../.pub-cache/hosted/pub.dev/build_runner_core-7.2.8/lib/src/logging/build_for_input_logger.dart:13:7: Error: The non-abstract class 'BuildForInputLogger' is missing implementations for these members:
 - Logger.onLevelChanged
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class BuildForInputLogger implements Logger {
      ^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/logging-1.2.0/lib/src/logger.dart:162:22: Context: 'Logger.onLevelChanged' is defined here.
  Stream<Level?> get onLevelChanged {
                     ^^^^^^^^^^^^^^
Failed to build build_runner:build_runner:
../../.pub-cache/hosted/pub.dev/build_runner_core-7.2.8/lib/src/logging/build_for_input_logger.dart:13:7: Error: The non-abstract class 'BuildForInputLogger' is missing implementations for these members:
 - Logger.onLevelChanged
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class BuildForInputLogger implements Logger {
      ^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/logging-1.2.0/lib/src/logger.dart:162:22: Context: 'Logger.onLevelChanged' is defined here.
  Stream<Level?> get onLevelChanged {
                     ^^^^^^^^^^^^^^

**Comment by ricardoamador** [comment]
@desistefanova thank you for the steps to upgrade!

**Comment by VikasAwate5** [comment]
on mac machine it didn't work. getting below response and nothing changes. ->

**Building package executable... 
Built realm:realm.**

**Comment by dotjon0** [comment]
> on mac machine it didn't work. getting below response and nothing changes. ->
> 
> **Building package executable... Built realm:realm.**

@VikasAwate5 if you see the resolution steps above which resolved this (I had exactly the same issue, thus this issue)
